server:
  port: 3000
  address: 0.0.0.0
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/customer
    username: luminahi
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
